version: '3.8'

services:
  api:
    image: ninepiece2/assetto-corsa-server-interface:api
    container_name: Assetto-Corsa-Server-Interface-API
    ports:
      - "8443:8443"
    volumes:
      - /root/certs:/https:ro
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    command: ["dotnet", "Assetto-Corsa-Server-Interface-API.dll"]
    restart: always

  ui:
    image: ninepiece2/assetto-corsa-server-interface:ui
    container_name: Assetto-Corsa-Server-Interface-UI
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BASE_URL=http://api:8080
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: always