version: '3.8'

services:
  api:
    image: ninepiece2/assetto-corsa-server-interface:api
    container_name: Assetto-Corsa-Server-Interface-API
    ports:
      - "8443:8443"
    volumes:
      - /root/certs:/https:ro
    environment:
      - ASPNETCORE_URLS=https://*:8443;http://*:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ssl.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/ssl.key
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    command: ["dotnet", "Assetto-Corsa-Server-Interface-API.dll"]
    restart: always

  ui:
    image: ninepiece2/assetto-corsa-server-interface:ui
    container_name: Assetto-Corsa-Server-Interface-UI
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BASE_URL=https://api:8443
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: always

  nginx:
    image: nginx:latest
    container_name: Nginx-Proxy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/certs:/etc/nginx/ssl:ro
    depends_on:
      - ui