name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Build-API:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./API/Assetto-Corsa-Server-Interface-API
          file: ./API/Assetto-Corsa-Server-Interface-API/Assetto-Corsa-Server-Interface-API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/assetto-corsa-server-interface:api

  Build-UI:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./UI
          file: ./UI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/assetto-corsa-server-interface:ui
          build-args: |
            SYNCFUSION_LICENSE=${{ secrets.SyncfusionLicense }}

  Deploy:
    runs-on: self-hosted
    needs: [Build-API, Build-UI]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Pull latest Docker images
        run: docker-compose pull

      - name: Remove Old Continer
        run: docker-compose down

      - name: Deploy with Docker Compose
        env:
          ASPNETCORE_ENVIRONMENT: ${{ secrets.ASPNETCORE_ENVIRONMENT }}
          SyncfusionLicense: ${{ secrets.SyncfusionLicense }}
        run: docker-compose up -d

      - name: Remove unused Docker images
        run: docker image prune -af